# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo_img_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 27, 12, 5, 34, 248882, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photodislike',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photolike',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
